### ISSUE TITLE
migrate() got an unexpected keyword argument 'empty'

### ISSUE THREAD

**Issue by itsvic-dev** [tortoise/aerich#329]
appears to have been broken since https://github.com/tortoise/aerich/commit/2b2e46536232832bd8e7c7e4e1a476dc92461677, will test with commit before that

**Comment by itsvic-dev** [comment]
yeah, works with parent commit https://github.com/tortoise/aerich/commit/ede53ade867f5e0a0a3f64c7363ab6decf5bd3c5

**Comment by mehdinourollah** [comment]
It's not working in any of the branches as I checked out to them ...Can someone tell me on which branch `--empty` works ?

**Comment by waketzheng** [comment]
This work:
```bash
pip install --upgrade "aerich>=0.8.0"
```
